apiVersion: v1
kind: Pod
metadata:
  name: {{appName}}
  labels:
    name: {{appName}}
    environment: {{env}}
    visualize: "true"
spec:
  containers:
    - resources:
        limits :
          cpu: 0.5
      image: mysql:5.6
      name: {{appName}}
      env:
      # kubectl create secret generic {{appName}}-secret --from-literal=username='my-app' --from-literal=password='39528$vdg7Jb
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{appName}}-secret
              key: rootpassword
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: {{appName}}-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{appName}}-secret
              key: password
        - name: MYSQL_DATABASE
          value: {{mysqlDatabase}}
      ports:
        - containerPort: 3306
          name: mysql
      volumeMounts:
          # name must match the volume name below
        - name: {{appName}}-persistent-storage
          # mount path within the container
          mountPath: /var/lib/mysql
  volumes:
    - name: {{appName}}-persistent-storage
      persistentVolumeClaim:
        claimName: {{appName}}-pvc
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{appName}}-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: pd-standard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100m