apiVersion: batch/v1
kind: Job
metadata:
  name: {{appName}}-job
  labels:
    name: {{appName}}-job
spec:
  template:
    metadata:
      labels:
        name: {{appName}}-job
    spec:
      containers:
      - name: test
        image: frolvlad/alpine-oraclejdk8:slim
        command: ["/bin/sh"]
        args: ["-c", "{{command}}"]
        env:
        - name: PAAS_TYPE
          value: "k8s"
        - name: APPLICATION_URL
          value: "http://{{appName}}"
        - name: STUBRUNNER_URL
          value: "http://{{stubrunnerName}}"
        volumeMounts:
          - mountPath: "/var/jenkins_home"
            name: user-smoke-volume
          - mountPath: "/root"
            name: root-smoke-volume
      volumes:
        - name: user-smoke-volume
          persistentVolumeClaim:
            claimName: user-smoke-volume-claim
        - name: root-smoke-volume
          persistentVolumeClaim:
            claimName: root-smoke-volume-claim
      restartPolicy: Never