apiVersion: v1
kind: Service
metadata:
  name: {{appName}}
  labels:
    name: {{appName}}
    env: {{env}}
    visualize: "true"
spec:
  ports:
    - port: 8080
  selector:
    app: {{appName}}
    env: {{env}}
  type: NodePort